In [1]:
using POMDPs, POMDPTools, QuickPOMDPs, MCTS, DiscreteValueIteration, POMDPSimulators, POMDPModels, POMDPPolicies
using Distributions, Combinatorics, StaticArrays, D3Trees, Random
using FileIO, JLD2, TickTock

In [2]:
action=[(0,0), (0,1), (1,1)]

Number_level = 10;
#Transition_matrix = [0.86 0.14 0.0 0.0; 0.0 0.83 0.17 0.0;0.0 0.0 0.89 0.11;1.0 0.0 0.0 0.0];

failure_penalty = -1000.0;
maintenance_penalty = -800.0;
setup_cost = -300.0;
normal_operation = 45.0;

In [3]:
function reward(s, a,k,s1=10, rng=23)       #s is a vector of number units at each level and a is the number of units we will repair
    p=[sum(1-T[i,i,1,j] for i in 1:9) for j in 1:NumberUnits]/sum(sum(1-T[i,i,1,j] for i in 1:9) for j in 1:NumberUnits)   
    if s==Number_level
            r=failure_penalty  + normal_operation  ;
        return r
       end
        r=0
     if a==1
        if s1>=s
            crd = Categorical(T[s,:,1,k]);
            s = rand(crd);
            r = normal_operation ;
         return r
        else
            return 0.0
        end
        end
    if a==2
        if s==1
            crd = Categorical(T[s,:,1,k]);
            s = rand(crd);
            r= normal_operation   ;
            return r
        else
        s1=deepcopy(s)
        s=1
        r = maintenance_penalty 
         crd = Categorical(T[s,:,1,k]);
            s = rand(crd);
            r+= normal_operation  ;
#            r*=(s1/10);
        return r
        end
    end
    end

reward (generic function with 3 methods)

In [4]:
s=1:Number_level;

In [5]:
T=zeros(Number_level,Number_level,2,100);

In [6]:
for i in 1:100
    fullname = "TM_MATRIX/tm"*string(i);
    # generate_transition_matrix(Number_level, fullname) 
    Transition_matrix = load(fullname*".jld2","transition_matrix");
    
    T[:,:,1,i].=Transition_matrix;
    T[:,:,2,i].=Transition_matrix;
    for j in 1:10
        T[j,:,2,i].=Transition_matrix[1,:];
        end
    T[10,:,1,i].=Transition_matrix[1,:]
T[10,:,2,i].=Transition_matrix[1,:]
end

In [7]:
T

10×10×2×100 Array{Float64, 4}:
[:, :, 1, 1] =
 0.232649  0.229122  0.130585  0.0954644  …  0.0507595  0.0416229  0.00861626
 0.0       0.218724  0.163234  0.128353      0.0899794  0.0431818  0.00868773
 0.0       0.0       0.166395  0.182476      0.111027   0.0773355  0.043199
 0.0       0.0       0.0       0.269557      0.125296   0.0981466  0.0533485
 0.0       0.0       0.0       0.0           0.125828   0.109077   0.0611228
 0.0       0.0       0.0       0.0        …  0.215491   0.17866    0.0619123
 0.0       0.0       0.0       0.0           0.352355   0.221208   0.0646198
 0.0       0.0       0.0       0.0           0.471891   0.449917   0.0781922
 0.0       0.0       0.0       0.0           0.0        0.591116   0.408884
 0.232649  0.229122  0.130585  0.0954644     0.0507595  0.0416229  0.00861626

[:, :, 2, 1] =
 0.232649  0.229122  0.130585  0.0954644  …  0.0507595  0.0416229  0.00861626
 0.232649  0.229122  0.130585  0.0954644     0.0507595  0.0416229  0.00861626
 0.232649  

In [8]:
function explore()
    c=[1/3,1/3,1/3]

     crd = Categorical(c);
     return rand(crd)
    end 
function generative(s, a,k, rng=23)       #s is a vector of number units at each level and a is the number of units we will repair
        if s==Number_level
        s=1
        crd = Categorical(T[s,:,1,k]);
            s = rand(crd);
            r=failure_penalty  + normal_operation  ;
        return (sp=s, r=r)
       end
        r=0
     if a==1
            crd = Categorical(T[s,:,1,k]);
            s = rand(crd);
            r = normal_operation ;
         return (sp=s, r=r)
        end
    if a==2
#         if s==1
#             crd = Categorical(T[s,:,1,k]);
#             s = rand(crd);
#             r= normal_operation+  setup_cost/NumberUnits  ;
#             return (sp=s, r=r)
#         else
        s1=deepcopy(s)
        s=1
        r = maintenance_penalty 
         crd = Categorical(T[s,:,1,k]);
            s = rand(crd);
            r+= normal_operation  ;
#            r*=(s1/10);
       return (sp=s, r=r)
#         end
    end
    end

generative (generic function with 2 methods)

In [9]:
function simulate!(V,a,T, s,S,γ, d)
    if d ≤ 0
        return sum(T[s,s1,1]*V[s1] for (s1) in S)
    end
#     a = explore()
#     print("IN")

    s′, r = generative(s,a)
    q = r + γ*simulate!(V,a,T, s′,S,γ, d-1)
#     print("out")
#     N[s,a] += 1
#     Q[s,a] += (q-Q[s,a])/N[s,a]
    return q
end

simulate! (generic function with 1 method)

In [10]:
function ValueIteration(S, T, γ, p1=0.01, d=100)
    Q=zeros((Number_level,2,NumberUnits))
#     print(Q)
    V= rand(Float64, (Number_level,NumberUnits))*1000
    diff=0
    i=0
    
    

    
    
   Threads.@threads for k in 1:NumberUnits
        p=[1 1 1 ]
    for i in 1:1500
#     while  i<=10000
    for s in 1:Number_level
        for a in 1:2
                Q[s,a,k]= (reward(s,a,k)) + γ*( sum(T[s,s1,a,k]*(V[s1,k]) for (s1) in 1:Number_level ))
        end
       V[s,k]=findmax(Q[s,1:2,k])[1]

        end
        
        end
    end
#     println(Q)
    return Q
    end

ValueIteration (generic function with 3 methods)

In [11]:
# function ValueIteration(S, T, γ, p1=0.01, d=100)
#     Q=zeros((Number_level,3,NumberUnits)).+100
# #     print(Q)
#     V= rand(Float64, (Number_level,NumberUnits))*1000
#     V1= rand(Float64, (Number_level,NumberUnits))*1000

#     diff=0
#     i=0
    
    

    
#      p=zeros(Float64, (Number_level,NumberUnits,3)).+(1/3)
#     for k in 1:NumberUnits
       
#     for i in 1:500
# #     while  i<=10000
#     for s in 1:Number_level
#         Threads.@threads for a in 1:3
#                 Q[s,a,k]= (reward(s,a,k)) + γ*( sum(T[s,s1,a,k]*(V[s1,k]) for (s1) in 1:Number_level ))
#         end
#             p[s,k,:]=[exp(lamb*sum(Q[s,1,k])),exp(lamb*sum(Q[s,2,k])),exp(lamb*sum(Q[s,3,k]))]
#             p[s,k,:]=p[s,k,:]./sum(p[s,k,:])
# #        V[s,k]=Q[s,1,k]*p[s,k,1]+max(Q[s,2,k],Q[s,3,k])*(p[s,k,2]+p[s,k,3])
#        V[s,k]=Q[s,1,k]*p[s,k,1]+max(Q[s,2,k],Q[s,3,k])*(p[s,k,2]+p[s,k,3])
# #         for s in 1:Number_level
# #         p1=[exp(lamb1*V[s,k]) for k in 1:NumberUnits]
# #         p1=p1./sum(p1)
# #         V[s,:].=sum([p1[k]*V[s,k] for k in 1:NumberUnits])
# # #         V[s,:].=min(V[s,:]...)#/NumberUnits
# #         end
#         end
# #         for s in 1:Number_level
# # #         p1=[exp(lamb1*V1[s,k]) for k in 1:NumberUnits]
# # #         p1=p1./sum(p1)
# # #         V[s,:].=sum([p1[k]*V1[s,k] for k in 1:NumberUnits])
# #         V[s,:].=mean(V1[s,:])#/NumberUnits
# #         end
#         end
#     end
#     return Q
#     end

In [12]:
 Q=ValueIteration(s,T,.95,0.01,3000)

LoadError: UndefVarError: NumberUnits not defined

In [13]:
global lamb=.1 
Q=ValueIteration(s,T,.95,1,1000)

LoadError: UndefVarError: NumberUnits not defined

In [14]:
s

1:10

In [15]:

# function decison(Q, s)
#    a_final=[]
#    if Number_level in s
# #         print("hi")
#         d=(collect(Iterators.product((Q[s[i],2:3] for i in 1:NumberUnits)...)))
#         d1=(collect(Iterators.product((2:3 for i in 1:NumberUnits)...)))
#         min=-1e+10
#         opt=0
#         for (i,j) in enumerate(d)
#             if min < sum((j))
#                 min=sum((j))
#                 opt=i
#             end
#         end
#         return d1[opt]
#     end
#     q0=0.0
#     a_0=repeat(1:1,NumberUnits);
#     for i in 1:NumberUnits
#             q0+=Q[s[i],1]
#     end
#     d=(collect(Iterators.product((Q[s[i],2:3] for i in 1:NumberUnits)...)))
#     d1=(collect(Iterators.product((2:3 for i in 1:NumberUnits)...)))
# #     d[1]=a_0
# #     print("here")
# #     d1[1]=(1,1,1,1,1,1,1,1,1,1)
#     min=-1e+10
#     opt=0
#     for (i,j) in enumerate(d)
#         if i==1
#             if min < q0
#             min=q0
#             opt=i
#         end
#         elseif min < sum((j))
#             min=sum((j))
#             opt=i
#         end
#     end
#     if opt==1
#         return a_0
#     else
#         return d1[opt]
#     end
#     return opt
# end


function decison(Q, s,n=0.2)
 a_final=[]
#         print("hi")
        for i in 1:NumberUnits
#         println/(i)
            append!(a_final,argmax(a->Q[s[i],a,i], [1,2]))
            end
        return a_final
end

decison (generic function with 2 methods)

In [16]:
decison(Q,[8,8
        ,8,8
        ,1,1,6,1, 7,7,8,8
        ,8,8
        ,1,1,6,1, 7,7])

LoadError: UndefVarError: Q not defined

In [17]:
Q

LoadError: UndefVarError: Q not defined

In [18]:
s

1:10

In [19]:
using DataFrames
df= DataFrame(Units=[],n=[],s=[],m=[],f=[],lambda=[],mean=[],std=[])

0×8 DataFrame
 Row │ Units  n    s    m    f    lambda  mean  std 
     │ Any    Any  Any  Any  Any  Any     Any   Any 
─────┴──────────────────────────────────────────────

In [20]:
cost=[ 
    [0 -1000 -200 -1000],
    [0 -1200 -200 -1000],
    [0 -1000 -200 -1400],
    [0 -1000 -200 -1600]
    
    ]

# print(Q)

for units in [60,50,40,30,20]
    for c in cost
   print(units)  
    global normal_operation,setup_cost,maintenance_penalty,failure_penalty=c
     println([normal_operation,setup_cost,maintenance_penalty,failure_penalty])   
     for lambda in 1:1:1
        global  lamb=lambda
    global NumberUnits=units
     Q=ValueIteration(s,T,.95,3000)
#          println(isnan(Q[1,1]))
#        if sum(isnan(Q[1,1]))>0.0
#             continue
#         end
tick()
trials=10000;
simsteps = 100;
results=zeros(trials)*0.1
Threads.@threads for h in 1:trials
s=repeat(1:1,NumberUnits)
r1=[]
a1=[]   
r=repeat(1:1,NumberUnits)*1.0
 for k in 1:simsteps
    a =decison(Q,s)
    r2=0.0
    s1=repeat(1:1,NumberUnits)
              
            
#     println(a)
    for i in 1:NumberUnits
#             print(generative(s[i],a[i],i))
         s1[i],r[i]=generative(s[i],a[i],i);
          r2+=r[i]
            end 
#     println(r2)
#     println(s)
    if (Number_level in s) || (2 in a)
            r2+=setup_cost
                    end
    s=s1;
    append!(a1,a)
    append!(r1,r2)
end
rk=0
for i in 1:simsteps
    rk=0.95*rk+r1[simsteps-i+1]
end
#     println(rk)
    results[h]=rk
#     println(results)
end
println(units)
println(lambda)

println(mean(results))

println(std(results))
pushfirst!(df,[units,normal_operation,setup_cost,maintenance_penalty,failure_penalty,lamb,mean(results),std(results)])
        
tock()
end
    println("-------------------------")
end
end

60[0, -1000, -200, -1000]


[ Info:  started timer at: 2023-04-02T14:08:57.636


60
1
-104004.80613544049
3747.0020955483433
-------------------------
60[0, -1200, -200, -1000]


[ Info:           93.3068463s: 1 minute, 33 seconds, 306 milliseconds
[ Info:  started timer at: 2023-04-02T14:15:23.692


60
1
-107839.62189725235
3737.347210558693
-------------------------

[ Info:           91.3950168s: 1 minute, 31 seconds, 395 milliseconds



60[0, -1000, -200, -1400]


[ Info:  started timer at: 2023-04-02T14:21:48.412


60
1
-118129.64318247767
4698.001860817273


[ Info:           87.7050641s: 1 minute, 27 seconds, 705 milliseconds


-------------------------
60[0, -1000, -200, -1600]


[ Info:  started timer at: 2023-04-02T14:28:10.031


60
1
-123860.90458108982
5148.897523319652
-------------------------
50[0, -1000, -200, -1000]


[ Info:           91.4579779s: 1 minute, 31 seconds, 457 milliseconds
[ Info:  started timer at: 2023-04-02T14:33:08.182


50
1
-90259.26641911779
3443.1932752644097
-------------------------
50[0, -1200, -200, -1000]


[ Info:            76.309961s: 1 minute, 16 seconds, 309 milliseconds
[ Info:  started timer at: 2023-04-02T14:37:51.365


50
1
-93988.72195506177
3497.2632272928586
-------------------------
50[0, -1000

[ Info:           76.4359095s: 1 minute, 16 seconds, 435 milliseconds


, -200, -1400]


[ Info:  started timer at: 2023-04-02T14:42:35.821


50
1
-102332.94023610964
4446.699256547157
-------------------------
50[0, -1000, -200, -1600]


[ Info:           76.4034286s: 1 minute, 16 seconds, 403 milliseconds
[ Info:  started timer at: 2023-04-02T14:47:19.802


50
1
-107189.02945386589
4731.0031342092425
-------------------------
40[0, -1000, -200, -1000]


[ Info:           76.4410658s: 1 minute, 16 seconds, 441 milliseconds
[ Info:  started timer at: 2023-04-02T14:50:42.252


40
1
-75844.89708231868
3074.007927414623


[ Info:           60.9414785s: 1 minute, 941 milliseconds


-------------------------
40[0, -1200, -200, -1000]


[ Info:  started timer at: 2023-04-02T14:53:50.743


40
1
-79549.14831788288
3081.8122604963096


[ Info:           59.2871277s: 59 seconds, 287 milliseconds


-------------------------
40[0, -1000, -200, -1400]


[ Info:  started timer at: 2023-04-02T14:57:08.524


40
1
-85241.58204968614
3912.0695292061932
-------------------------

[ Info:           61.0549758s: 1 minute, 1 second, 54 milliseconds



40[0, -1000, -200, -1600]


[ Info:  started timer at: 2023-04-02T15:00:13.968


40
1
-89282.24126592383
4277.613608898447
-------------------------
30[0, -1000, -200, -1000]


[ Info:           60.9953938s: 1 minute, 995 milliseconds
[ Info:  started timer at: 2023-04-02T15:02:30.378


30
1
-63384.32319557967
2678.8645631915947
-------------------------
30

[ Info:           43.5158817s: 43 seconds, 515 milliseconds


[0, -1200, -200, -1000]


[ Info:  started timer at: 2023-04-02T15:04:27.924


30
1
-67135.3036015796
2702.709654564808
-------------------------
30[0, -1000, -200, -1400]


[ Info:           45.5006916s: 45 seconds, 500 milliseconds
[ Info:  started timer at: 2023-04-02T15:06:28.365


30
1
-70415.76060368506
3388.27168580949


[ Info:           45.7883273s: 45 seconds, 788 milliseconds


-------------------------
30[0, -1000, -200, -1600]


[ Info:  started timer at: 2023-04-02T15:08:25.434


30
1
-73521.15275638139
3711.1828925813147
-------------------------
20[0, -1000, -200, -1000]


[ Info:           45.2871075s: 45 seconds, 287 milliseconds
[ Info:  started timer at: 2023-04-02T15:09:46.789


20
1
-48378.740595289055
2265.4552104632226
-------------------------
20[0, -1200, -200, -1000]


[ Info:           30.8080058s: 30 seconds, 808 milliseconds
[ Info:  started timer at: 2023-04-02T15:10:53.236


20
1
-52100.231235344385
2263.581010310045


[ Info:            30.706682s: 30 seconds, 706 milliseconds


-------------------------
20[0, -1000, -200, -1400]


[ Info:  started timer at: 2023-04-02T15:11:59.698


20
1
-53296.10982618733
2916.5412716679043
-------------------------
20[0

[ Info:           27.9988228s: 27 seconds, 998 milliseconds


, -1000, -200, -1600]


[ Info:  started timer at: 2023-04-02T15:13:03.113


20
1
-55390.2108401892
3095.2940479918007
-------------------------


[ Info:           30.7592844s: 30 seconds, 759 milliseconds


In [21]:
df

20×8 DataFrame
 Row │ Units  n    s        m       f        lambda  mean        std     
     │ Any    Any  Any      Any     Any      Any     Any         Any     
─────┼───────────────────────────────────────────────────────────────────
   1 │ 20.0   0.0  -1000.0  -200.0  -1600.0  1.0     -55390.2    3095.29
   2 │ 20.0   0.0  -1000.0  -200.0  -1400.0  1.0     -53296.1    2916.54
   3 │ 20.0   0.0  -1200.0  -200.0  -1000.0  1.0     -52100.2    2263.58
   4 │ 20.0   0.0  -1000.0  -200.0  -1000.0  1.0     -48378.7    2265.46
   5 │ 30.0   0.0  -1000.0  -200.0  -1600.0  1.0     -73521.2    3711.18
   6 │ 30.0   0.0  -1000.0  -200.0  -1400.0  1.0     -70415.8    3388.27
   7 │ 30.0   0.0  -1200.0  -200.0  -1000.0  1.0     -67135.3    2702.71
   8 │ 30.0   0.0  -1000.0  -200.0  -1000.0  1.0     -63384.3    2678.86
   9 │ 40.0   0.0  -1000.0  -200.0  -1600.0  1.0     -89282.2    4277.61
  10 │ 40.0   0.0  -1000.0  -200.0  -1400.0  1.0     -85241.6    3912.07
  11 │ 40.0   0.0  -1200.0  -200.0  -1000.0  1.0     -79549.1    3081.81
  12 │ 40.0   0.0  -1000.0  -200.0  -1000.0  1.0     -75844.9    3074.01
  13 │ 50.0   0.0  -1000.0  -200.0  -1600.0  1.0     -107189.0   4731.0
  14 │ 50.0   0.0  -1000.0  -200.0  -1400.0  1.0     -1.02333e5  4446.7
  15 │ 50.0   0.0  -1200.0  -200.0  -1000.0  1.0     -93988.7    3497.26
  16 │ 50.0   0.0  -1000.0  -200.0  -1000.0  1.0     -90259.3    3443.19
  17 │ 60.0   0.0  -1000.0  -200.0  -1600.0  1.0     -1.23861e5  5148.9
  18 │ 60.0   0.0  -1000.0  -200.0  -1400.0  1.0     -1.1813e5   4698.0
  19 │ 60.0   0.0  -1200.0  -200.0  -1000.0  1.0     -1.0784e5   3737.35
  20 │ 60.0   0.0  -1000.0  -200.0  -1000.0  1.0     -1.04005e5  3747.0

In [22]:
using CSV
CSV.write("independent with setup DISJOINT.csv", df)

"independent with setup DISJOINT.csv"

In [23]:
 Q=ValueIteration(s,T,.95,3000)
for s in 1:Number_level
p=[exp(0.01*sum(Q[s,1])),exp(0.01*sum(Q[s,2])),exp(0.01*sum(Q[s,3]))]
    p./=sum(p)
    println(p)
end

LoadError: BoundsError: attempt to access 10×2×20 Array{Float64, 3} at index [1, 1]

In [24]:
df[df.Units.==15,:]

0×8 DataFrame
 Row │ Units  n    s    m    f    lambda  mean  std 
     │ Any    Any  Any  Any  Any  Any     Any   Any 
─────┴──────────────────────────────────────────────

In [25]:
df1= DataFrame(Units=[],mean=[])
for i in [2,4,5,8,10,15,20,25,30]
    pushfirst!(df1,[i,findmax(df[df.Units.==i,:].mean)[1]])
end
CSV.write("valueiteration_softmax_space_division_FINAL.csv", df1)

LoadError: MethodError: reducing over an empty collection is not allowed; consider supplying `init` to the reducer

In [26]:
df1

0×2 DataFrame
 Row │ Units  mean 
     │ Any    Any  
─────┴─────────────