In [1]:
using POMDPs, POMDPTools, QuickPOMDPs, MCTS, DiscreteValueIteration, POMDPSimulators, POMDPModels, POMDPPolicies
using Distributions, Combinatorics, StaticArrays, D3Trees, Random
using FileIO, JLD2, TickTock

In [2]:
action=[(0,0), (0,1), (1,1)]

Number_level = 4;
#Transition_matrix = [0.86 0.14 0.0 0.0; 0.0 0.83 0.17 0.0;0.0 0.0 0.89 0.11;1.0 0.0 0.0 0.0];
fullname = "tm10";
# generate_transition_matrix(Number_level, fullname) 
global Transition_matrix = 
            [0.8571 0.1429 0 0;
        0 0.8571 0.1429 0;
        0 0 0.8 0.2
      0 0 0 1];
Transition_matrix=Transition_matrix./[sum(Transition_matrix[i,:]) for i in 1:4]
failure_penalty = -1000.0;
maintenance_penalty = -200.0;
setup_cost = -800.0;
normal_operation = 0.0;

In [6]:
function reward(s, a,s1=10, rng=23)       #s is a vector of number units at each level and a is the number of units we will repair
       if s==Number_level
            r=failure_penalty +  setup_cost/NumberUnits  + normal_operation  ;
        return r
       end
        r=0
     if a==1
        if s1>=s
            crd = Categorical(Transition_matrix[s,:]);
            s = rand(crd);
            r = normal_operation ;
         return r
        else
            return 0.0
        end
        end
    if a==2
         if s1>=s
            crd = Categorical(Transition_matrix[s,:]);
            s = rand(crd);
            r = normal_operation +  setup_cost/NumberUnits;
         return r
        else
            return 0.0
        end
        end
    if a==3
        s1=deepcopy(s)
        s=1
        r = maintenance_penalty +  setup_cost/NumberUnits
         crd = Categorical(Transition_matrix[s,:]);
            s = rand(crd);
            r+= normal_operation  ;
#            r*=(s1/10);
        return r
    end
    end

reward (generic function with 3 methods)

In [9]:
(Transition_matrix)

4×4 Matrix{Float64}:
 0.8571  0.1429  0.0     0.0
 0.0     0.8571  0.1429  0.0
 0.0     0.0     0.8     0.2
 0.0     0.0     0.0     1.0

In [10]:
T=zeros(Number_level,Number_level,3);


In [11]:
((1:10)./10)

0.1:0.1:1.0

In [12]:
T[:,:,1].=Transition_matrix;

In [13]:
T[:,:,2].=Transition_matrix;

In [14]:
for j in 1:4
        T[j,:,3].=Transition_matrix[1,:];
        end
# for j in 1:10
#         T[j,:,3].=0.0
#     T[j,1,3]=1.0
#         end

In [15]:
T[4,:,1].=Transition_matrix[1,:]
T[4,:,2].=Transition_matrix[1,:]

4-element view(::Array{Float64, 3}, 4, :, 2) with eltype Float64:
 0.8571
 0.1429
 0.0
 0.0

In [19]:
function explore()
    c=[1/3,1/3,1/3]

     crd = Categorical(c);
     return rand(crd)
    end 
function generative(s, a, rng=23)       #s is a vector of number units at each level and a is the number of units we will repair
        if s==Number_level
        s=1
        crd = Categorical(Transition_matrix[s,:]);
            s = rand(crd);
            r=failure_penalty +  setup_cost/NumberUnits + normal_operation  ;
        return (sp=s, r=r)
       end
        r=0
     if a==1
            crd = Categorical(Transition_matrix[s,:]);
            s = rand(crd);
            r = normal_operation ;
         return (sp=s, r=r)
        end
    if a==2
            crd = Categorical(Transition_matrix[s,:]);
            s = rand(crd);
            r = normal_operation +  setup_cost/NumberUnits ;
             return (sp=s, r=r)
        end
    if a==3
        s1=deepcopy(s)
        s=1
        r = maintenance_penalty +  setup_cost/NumberUnits
         crd = Categorical(Transition_matrix[s,:]);
            s = rand(crd);
            r+= normal_operation  ;
#            r*=(s1/10);
       return (sp=s, r=r)
    end
    end

generative (generic function with 2 methods)

In [25]:
function ValueIteration(S, T, γ, p1=0.01, d=100)
    Q=zeros((Number_level,3))
#     print(Q)
    V= rand(Float64, (Number_level))*1000
    diff=0
    i=0
    
    

    
    p=[1 1 1 ]
    while i<=2000
#     while  i<=10000
    for s in 1:4
        Threads.@threads for a in 1:3
 
                Q[s,a]= (reward(s,a)) + γ*( sum(T[s,s1,a]*(V[s1]) for (s1) in 1:4 ))
    end
            V[s]=findmax(Q[s,1:3])[1]
        end
        i+=1
        end
    return Q,V
    end

ValueIteration (generic function with 3 methods)

In [33]:


function decison(Q, s,n=0.2)
   a_final=[]
   if Number_level in s
#         print("hi")
        for i in 1:NumberUnits
            append!(a_final,argmax(a->Q[s[i],a], [2,3]))
            end
        return a_final
    end
    q0=0.0
    a_0=repeat(1:1,NumberUnits);
    for i in 1:NumberUnits
            q0+=Q[s[i],1]
    end
    a_final=repeat(1:1,NumberUnits);
    repair= argmax(i->s[i], 1:NumberUnits)
#     print(repair)
    a_final[repair]=3
    b=1
    for i in 1:NumberUnits
            if i!=repair
            a_final[i]=argmax(a->Q[s[i],a], [2,3])
#             println(s[i])
#             println(a_final[i])

            if a_final[i]==3
                b+=1
            end
            end
    end
        q1=0.0
    for i in 1:NumberUnits
            q1+=Q[s[i],a_final[i]]
    end
#     if b<=NumberUnits*n
#         return a_0
#     end
    if q0>q1
            return a_0
        else
            return a_final
        end
end

decison (generic function with 2 methods)

In [35]:
using DataFrames
df= DataFrame(Units=[],n=[],s=[],m=[],f=[],lambda=[],mean=[],std=[])

0×8 DataFrame
 Row │ Units  n    s    m    f    lambda  mean  std 
     │ Any    Any  Any  Any  Any  Any     Any   Any 
─────┴──────────────────────────────────────────────

In [37]:

cost=[ 
     [0 -200 -200 -1000],
    [0 -400 -200 -1000],
    [0 -600 -200 -1000],
    [0 -800 -200 -1000],
    [0 -1000 -200 -1000],
    [0 -1200 -200 -1000],
    [0 -1400 -200 -1000],
    [0 -1600 -200 -1000]
    ]


for units in [3,5,10,15,20,25,30,40,50,60,70,80,100,125,150,175,200]
    for c in cost
   print(units)  
    global normal_operation,setup_cost,maintenance_penalty,failure_penalty=c
     println([normal_operation,setup_cost,maintenance_penalty,failure_penalty])   
     for lambda in 1:1:1
        global  lamb=lambda
    global NumberUnits=units
     Q,V=ValueIteration(s,T,.95,3000)
         println(isnan(Q[1,1]))
       if sum(isnan(Q[1,1]))>0.0
            continue
        end
tick()
trials=10000;
simsteps = 100;
results=zeros(trials)*0.1
Threads.@threads for h in 1:trials
s=repeat(1:1,NumberUnits)
r1=[]
a1=[]   
r=repeat(1:1,NumberUnits)*1.0
 for k in 1:simsteps
    a =decison(Q,s)
            r2=0.0
#     print(a)
    for i in 1:NumberUnits
#             print(generative(s[i],a[i],234))
         s[i],r[i]=generative(s[i],a[i],234);
          r2+=r[i]
            end 
#     println(r2)
#     println(s)
    s=s;
    append!(a1,a)
    append!(r1,r2)
end
rk=0
for i in 1:simsteps
    rk=0.95*rk+r1[simsteps-i+1]
end
#     println(rk)
    results[h]=rk
#     println(results)
end
println(units)
println(lambda)

println(mean(results))

println(std(results))
pushfirst!(df,[units,normal_operation,setup_cost,maintenance_penalty,failure_penalty,lamb,mean(results),std(results)])
        
tock()
end
    println("-------------------------")
end
end

3[0, -200, -200, -1000]
false


[ Info:  started timer at: 2023-03-24T10:13:18.136


3
1
-1767.9221243510785
572.6439403540659
-------------------------
3[0, -400, -200, -1000]


[ Info:             3.017809s: 3 seconds, 17 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:13:21.346


3
1
-2147.3646110127224
661.2175905521957
-------------------------
3[0, -600, -200, -1000]


[ Info:            1.9517989s: 1 second, 951 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:13:23.513


3
1
-2519.865332293386
761.8500785950116
-------------------------
3[0, -800, -200, -1000]


[ Info:            2.0002848s: 2 seconds


false


[ Info:  started timer at: 2023-03-24T10:13:25.629


3
1
-3022.928439154455
883.3215218711682
-------------------------
3[0, -1000, -200, -1000]


[ Info:            1.9732236s: 1 second, 973 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:13:27.747


3
1
-3092.1574829717165
864.8806413560167
-------------------------
3[0, -1200, -200, -1000]


[ Info:            2.0210059s: 2 seconds, 21 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:13:30.038


3
1
-3369.1563258859605
951.3471093466253
-------------------------
3[0, -1400, -200, -1000]


[ Info:            1.9845338s: 1 second, 984 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:13:32.195


3
1
-3659.6723013052574
1031.4953775546803
-------------------------
3[0, -1600, -200, -1000]


[ Info:            1.9723218s: 1 second, 972 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:13:34.271


3
1
-3941.79502033733
1100.950165355226
-------------------------
5[0, -200, -200, -1000]


[ Info:            2.0654806s: 2 seconds, 65 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:13:36.604


5
1
-2518.282193854315
638.5145531838898
-------------------------
5[0, -400, -200, -1000]


[ Info:            3.1563873s: 3 seconds, 156 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:13:39.914


5
1
-3084.2551662096025
738.2093316899909
-------------------------
5[0, -600, -200, -1000]


[ Info:            3.2570994s: 3 seconds, 257 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:13:43.300


5
1
-3835.7459875055915
904.6971825161845
-------------------------
5[0, -800, -200, -1000]


[ Info:            3.1341932s: 3 seconds, 134 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:13:46.668


5
1
-4296.725651999051
1001.5312902555509
-------------------------
5[0, -1000, -200, -1000]


[ Info:            3.3130324s: 3 seconds, 313 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:13:50.107


5
1
-4860.494048610873
1115.2608680073697
-------------------------
5[0, -1200, -200, -1000]


[ Info:            3.5032325s: 3 seconds, 503 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:13:53.769


5
1
-5291.932436057775
1210.366379676921
-------------------------
5[0, -1400,

[ Info:            3.1916844s: 3 seconds, 191 milliseconds


 -200, -1000]
false


[ Info:  started timer at: 2023-03-24T10:13:57.088


5
1
-5112.08994495595
1130.1786384330856


[ Info:            3.6266141s: 3 seconds, 626 milliseconds


-------------------------
5[0, -1600, -200, -1000]
false


[ Info:  started timer at: 2023-03-24T10:14:00.875


5
1
-5477.484919114904
1204.19884991798
-------------------------
10[0, -200, -200, -1000]


[ Info:            3.4140983s: 3 seconds, 414 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:14:04.425


10
1
-4118.567304650115
711.7619082581072
-------------------------
10[0, -400, -200, -1000]


[ Info:            6.5872935s: 6 seconds, 587 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:14:11.119


10
1
-5393.945750490896
935.5914556923528
-------------------------
10[0, -600, -200, -1000]


[ Info:            6.4740252s: 6 seconds, 474 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:14:17.725


10
1
-6351.912527677902
1076.6982013756783
-------------------------
10[0, -800, -200, -1000]


[ Info:            6.3402615s: 6 seconds, 340 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:14:24.183


10
1
-7044.331847764978
1162.0537608472373
-------------------------
10[0, -1000, -200, -1000]


[ Info:            6.3343128s: 6 seconds, 334 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:14:30.670


10
1
-7798.565320723513
1290.9979715601821
-------------------------
10[0, -1200, -200, -1000]


[ Info:            6.4472016s: 6 seconds, 447 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:14:37.236


10
1
-8514.956649246746
1399.8040603374836
-------------------------
10[0, -1400, -200, -1000]


[ Info:            6.3693412s: 6 seconds, 369 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:14:43.724


10
1
-9128.598995589195
1491.196234054632
-------------------------
10[0, -1600, -200, -1000]


[ Info:            6.2716491s: 6 seconds, 271 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:14:50.147


10
1
-9762.23286415762
1610.4404883261334
-------------------------
15[0, -200, -200, -1000]


[ Info:            6.5059788s: 6 seconds, 505 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:14:56.757


15
1
-5578.603361822271
743.3902213007669
-------------------------
15[0, -400, -200, -1000]


[ Info:            9.9481076s: 9 seconds, 948 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:15:06.841


15
1
-7132.647214979598
989.9491114667803
-------------------------
15[0, -600, -200, -1000]


[ Info:            9.6519117s: 9 seconds, 651 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:15:16.621


15
1
-8306.693930229992
1148.801700592994
-------------------------
15[0, -800, -200, -1000]


[ Info:            9.4295101s: 9 seconds, 429 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:15:26.206


15
1
-9374.813033881239
1297.431950358074
-------------------------
15[0, -1000, -200, -1000]


[ Info:            9.3609468s: 9 seconds, 360 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:15:35.694


15
1
-10275.630378951852
1391.0111004131086
-------------------------
15[0, -1200, -200, -1000]


[ Info:            9.5204035s: 9 seconds, 520 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:15:45.371


15
1
-11065.55164282636
1490.4646222813374
-------------------------
15[0, -1400, -200, -1000]


[ Info:            9.3684941s: 9 seconds, 368 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:15:54.834


15
1
-11902.432169045534
1576.8258638625514
-------------------------
15[0, -1600, -200, -1000]


[ Info:            9.2358807s: 9 seconds, 235 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:16:04.188


15
1
-12657.708423874325
1700.92052905568
-------------------------
20[0, -200, -200, -1000]


[ Info:            9.2833064s: 9 seconds, 283 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:16:13.604


20
1
-6991.488203933614
772.226498131083
-------------------------
20[0, -400, -200, -1000]


[ Info:           13.5491429s: 13 seconds, 549 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:16:27.273


20
1
-8723.562470213776
1026.9240973298406
-------------------------
20

[ Info:           12.9824715s: 12 seconds, 982 milliseconds


[0, -600, -200, -1000]
false


[ Info:  started timer at: 2023-03-24T10:16:40.387


20
1
-10123.172415945208
1208.7042819345843
-------------------------
20[0, -800, -200, -1000]


[ Info:            12.702461s: 12 seconds, 702 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:16:53.248


20
1
-11347.842557134425
1339.2570930924257
-------------------------
20[0, -1000, -200, -1000]


[ Info:           12.6103047s: 12 seconds, 610 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:17:05.979


20
1
-12436.112328415544
1444.0546099500198
-------------------------
20[0, -1200, -200, -1000]


[ Info:           12.6257654s: 12 seconds, 625 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:17:18.710


20
1
-13396.17785203987
1569.8635276528946
-------------------------
20[0, -1400, -200, -1000]


[ Info:           12.3863704s: 12 seconds, 386 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:17:31.190


20
1
-14325.62490487793
1659.5034944861602
-------------------------
20[0, -1600, -200, -1000]


[ Info:           12.4252475s: 12 seconds, 425 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:17:43.761


20
1
-15245.45442884097
1767.4827318302446
-------------------------
25[0, -200, -200, -1000]


[ Info:           12.6521787s: 12 seconds, 652 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:17:56.510


25
1
-8343.034697748395
801.0986520047177
-------------------------
25[0, -400, -200, -1000]


[ Info:           16.8165196s: 16 seconds, 816 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:18:13.433


25
1
-10254.19369604641
1057.4500825077614
-------------------------
25[0, -600, -200, -1000]


[ Info:           16.2781688s: 16 seconds, 278 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:18:29.822


25
1
-11809.55572329471
1217.4097757879106
-------------------------
25[0, -800, -200, -1000]


[ Info:           16.0490805s: 16 seconds, 49 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:18:45.998


25
1
-13325.873274964088
1429.1285181682179
-------------------------
25[0, -1000, -200, -1000]


[ Info:           15.6281352s: 15 seconds, 628 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:19:01.762


25
1
-14514.081019875759
1537.0134538430532
-------------------------
25[0, -1200, -200, -1000]


[ Info:           15.4374768s: 15 seconds, 437 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:19:17.369


25
1
-15471.7099102251
1623.8249191928012
-------------------------
25[0, -1400, -200, -1000]


[ Info:           15.5691556s: 15 seconds, 569 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:19:33.064


25
1
-16528.60748839231
1730.0509077216163
-------------------------
25[0, -1600, -200, -1000]


[ Info:           15.5548173s: 15 seconds, 554 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:19:48.738


25
1
-17534.180776809197
1830.5470553736336
-------------------------
30[0, -200, -200, -1000]


[ Info:           15.4217395s: 15 seconds, 421 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:20:04.298


30
1
-9661.46604277195
821.17927274434
-------------------------
30[0, -400, -200, -1000]


[ Info:           20.5883219s: 20 seconds, 588 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:20:24.996


30
1
-11750.873591920488
1054.1782712048046
-------------------------
30[0, -600, -200, -1000]


[ Info:           19.7082364s: 19 seconds, 708 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:20:44.837


30
1
-13619.66690473081
1324.0760019846432
-------------------------
30[0, -800, -200, -1000]


[ Info:           18.7939017s: 18 seconds, 793 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:21:03.780


30
1
-15056.483267043275
1453.7740277792138
-------------------------
30[0, -1000, -200, -1000]


[ Info:           18.8095871s: 18 seconds, 809 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:21:22.720


30
1
-16323.097689062757
1572.2475822400074
-------------------------
30[0, -1200, -200, -1000]


[ Info:           18.6053963s: 18 seconds, 605 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:21:41.469


30
1
-17503.95350388349
1676.212088123317
-------------------------
30[0, -1400, -200, -1000]


[ Info:           18.8230488s: 18 seconds, 823 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:22:00.454


30
1
-18622.230745613997
1786.561417920569
-------------------------
30[0, -1600, -200, -1000]


[ Info:           18.5757752s: 18 seconds, 575 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:22:19.143


30
1
-19681.46729285988
1864.7055629421804
-------------------------
40

[ Info:           18.7378771s: 18 seconds, 737 milliseconds


[0, -200, -200, -1000]
false


[ Info:  started timer at: 2023-03-24T10:22:37.988


40
1
-12190.692346757889
844.0865099055699
-------------------------
40[0, -400, -200, -1000]


[ Info:           27.9193563s: 27 seconds, 919 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:23:06.039


40
1
-14597.839030956442
1089.6793078168357
-------------------------
40[0, -600, -200, -1000]


[ Info:           26.7854744s: 26 seconds, 785 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:23:32.941


40
1
-16669.213405864495
1372.258765963329
-------------------------
40

[ Info:           25.6190308s: 25 seconds, 619 milliseconds


[0, -800, -200, -1000]
false


[ Info:  started timer at: 2023-03-24T10:23:58.683


40
1
-18286.222537245274
1524.056705102279
-------------------------
40[0, -1000, -200, -1000]


[ Info:           25.1419936s: 25 seconds, 141 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:24:23.962


40
1
-19785.246583512406
1631.932357333456
-------------------------
40[0, -1200, -200, -1000]


[ Info:           25.3881713s: 25 seconds, 388 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:24:49.470


40
1
-21165.9317033242
1735.9600024269664
-------------------------
40[0, -1400, -200, -1000]
false


[ Info:           26.8832705s: 26 seconds, 883 milliseconds
[ Info:  started timer at: 2023-03-24T10:25:16.445


40
1
-22402.537996925574
1825.7525455875277
-------------------------
40[0, -1600, -200, -1000]


[ Info:           24.6988753s: 24 seconds, 698 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:25:41.275


40
1
-23689.661384046234
1933.2596254028285
-------------------------
50[0, -200, -200, -1000]


[ Info:           24.8087441s: 24 seconds, 808 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:26:06.187


50
1
-14625.195055398022
873.0135519135404
-------------------------
50[0, -400, -200, -1000]


[ Info:           34.9375964s: 34 seconds, 937 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:26:41.217


50
1
-17297.274695829055
1107.2841271925565
-------------------------
50[0, -600, -200, -1000]


[ Info:             33.86638s: 33 seconds, 866 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:27:15.210


50
1
-19556.145488573347
1401.7587665266706
-------------------------
50[0, -800, -200, -1000]


[ Info:           32.0794993s: 32 seconds, 79 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:27:47.448


50
1
-21385.872387216918
1554.0237773346967
-------------------------
50[0, -1000, -200, -1000]


[ Info:           31.8714201s: 31 seconds, 871 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:28:19.453


50
1
-23008.508092798173
1687.5838805295734
-------------------------
50[0, -1200, -200, -1000]


[ Info:           31.5310954s: 31 seconds, 531 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:28:51.116


50
1
-24531.636466640866
1784.455272846341
-------------------------
50[0, -1400, -200, -1000]


[ Info:           31.1254052s: 31 seconds, 125 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:29:22.338


50
1
-26033.760056290088
1884.092702366645
-------------------------
50[0, -1600, -200, -1000]


[ Info:            30.739381s: 30 seconds, 739 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:29:53.181


50
1
-27354.307170382344
1996.4121456472049
-------------------------
60[0, -200, -200, -1000]
false


[ Info:            30.806638s: 30 seconds, 806 milliseconds
[ Info:  started timer at: 2023-03-24T10:30:24.065


60
1
-17004.420560897674
907.0116153995017
-------------------------

[ Info:           42.1680666s: 42 seconds, 168 milliseconds



60[0, -400, -200, -1000]
false


[ Info:  started timer at: 2023-03-24T10:31:06.405


60
1
-19897.626725929313
1094.7709557400467
-------------------------
60[0, -600, -200, -1000]


[ Info:           41.4078263s: 41 seconds, 407 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:31:47.933


60
1
-22308.166831321567
1407.192357760418
-------------------------
60[0, -800, -200, -1000]


[ Info:           39.1018213s: 39 seconds, 101 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:32:27.164


60
1
-24331.213731378793
1577.5126125110846
-------------------------
60[0, -1000, -200, -1000]


[ Info:           38.4303671s: 38 seconds, 430 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:33:05.693


60
1
-26060.895596492956
1717.8050346665107
-------------------------
60[0, -1200, -200, -1000]


[ Info:           37.7599825s: 37 seconds, 759 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:33:43.559


60
1
-27844.345205113448
1853.6450009282837


[ Info:           37.3320256s: 37 seconds, 332 milliseconds


-------------------------
60[0, -1400, -200, -1000]
false


[ Info:  started timer at: 2023-03-24T10:34:21.032


60
1
-29385.394662342405
1958.9059962825952
-------------------------
60[0, -1600, -200, -1000]


[ Info:           36.9060165s: 36 seconds, 906 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:34:58.042


60
1
-30791.71317061376
2027.50784165255
-------------------------
70[0, -200, -200, -1000]


[ Info:           36.9649231s: 36 seconds, 964 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:35:35.131


70
1
-19365.153976061792
953.8988710593314
-------------------------
70[0, -400, -200, -1000]


[ Info:           49.4251019s: 49 seconds, 425 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:36:24.687


70
1
-22423.866180921425
1094.9481823058895
-------------------------
70[0, -600, -200, -1000]


[ Info:           48.4252181s: 48 seconds, 425 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:37:13.244


70
1
-25024.46271269936
1419.1415111256738
-------------------------
70[0, -800, -200, -1000]


[ Info:           46.2022677s: 46 seconds, 202 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:37:59.592


70
1
-27202.318820906847
1602.1625151208757
-------------------------
70[0, -1000, -200, -1000]


[ Info:           45.2270896s: 45 seconds, 227 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:38:44.951


70
1
-29071.14825527215
1758.3212139294233
-------------------------
70[0, -1200, -200, -1000]


[ Info:           44.2961945s: 44 seconds, 296 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:39:29.363


70
1
-30949.777530565
1924.6791484933658
-------------------------
70[0, -1400, -200, -1000]


[ Info:           43.5276879s: 43 seconds, 527 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:40:13.011


70
1
-32520.477679762735
1999.8404877122414
-------------------------
70[0, -1600, -200, -1000]


[ Info:           43.0747992s: 43 seconds, 74 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:40:56.203


70
1
-34099.861373757005
2081.3946471839845
-------------------------
80[0, -200, -200, -1000]


[ Info:           43.2483635s: 43 seconds, 248 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:41:39.542


80
1
-21685.11061823981
979.3095818417082


[ Info:           56.9854501s: 56 seconds, 985 milliseconds


-------------------------
80[0, -400, -200, -1000]
false


[ Info:  started timer at: 2023-03-24T10:42:36.660


80
1
-24887.341069936167
1136.1687123668032
-------------------------
80[0, -600, -200, -1000]


[ Info:           56.0650007s: 56 seconds, 65 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:43:32.815


80
1
-27635.70952912895
1411.684753622182
-------------------------
80[0, -800, -200, -1000]


[ Info:             53.86041s: 53 seconds, 860 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:44:26.792


80
1
-29925.379321336426
1633.9845737198061
-------------------------
80[0, -1000, -200, -1000]
false


[ Info:           52.4133988s: 52 seconds, 413 milliseconds
[ Info:  started timer at: 2023-03-24T10:45:19.314


80
1
-32086.71080896291
1829.3290240274014
-------------------------
80[0, -1200, -200, -1000]


[ Info:           50.4966832s: 50 seconds, 496 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:46:09.915


80
1
-33922.7154834853
1940.373541155386
-------------------------
80[0, -1400, -200, -1000]


[ Info:           50.1901881s: 50 seconds, 190 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:47:00.200


80
1
-35643.0370792562
2009.9852828343085
-------------------------
80[0, -1600, -200, -1000]


[ Info:            50.264662s: 50 seconds, 264 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:47:50.583


80
1
-37273.01567030989
2140.693091759166
-------------------------
100[0, -200, -200, -1000]


[ Info:           49.7937914s: 49 seconds, 793 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:48:40.521


100
1
-26306.316472674094
1067.96318355397
-------------------------
100[0, -400, -200, -1000]
false


[ Info:           70.9223488s: 1 minute, 10 seconds, 922 milliseconds
[ Info:  started timer at: 2023-03-24T10:49:51.603


100
1
-29640.59497246132
1154.7452531700444
-------------------------
100[0, -600, -200, -1000]


[ Info:           70.7224773s: 1 minute, 10 seconds, 722 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:51:02.405


100
1
-32662.109334360033
1398.0991368991236
-------------------------

[ Info:           68.9529097s: 1 minute, 8 seconds, 952 milliseconds



100[0, -800, -200, -1000]
false


[ Info:  started timer at: 2023-03-24T10:52:11.483


100
1
-35315.861851592505
1605.188207978157
-------------------------
100[0, -1000, -200, -1000]


[ Info:           67.4203234s: 1 minute, 7 seconds, 420 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:53:19.035


100
1
-37727.0588642296
1909.8071476885805
-------------------------
100

[ Info:           64.2659155s: 1 minute, 4 seconds, 265 milliseconds


[0, -1200, -200, -1000]
false


[ Info:  started timer at: 2023-03-24T10:54:23.413


100
1
-39710.03139656336
1984.7430883294446
-------------------------
100[0, -1400, -200, -1000]


[ Info:           63.2779366s: 1 minute, 3 seconds, 277 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:55:26.835


100
1
-41600.581208456126
2088.873114279394
-------------------------
100[0, -1600, -200, -1000]


[ Info:            62.447838s: 1 minute, 2 seconds, 447 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:56:29.415


100
1
-43503.79064376831
2224.2497604719856
-------------------------
125[0, -200, -200, -1000]


[ Info:           61.8057046s: 1 minute, 1 second, 805 milliseconds


false


[ Info:  started timer at: 2023-03-24T10:57:31.314


125
1
-32011.603876355755
1173.850614940427


[ Info:           88.7189128s: 1 minute, 28 seconds, 718 milliseconds


-------------------------
125[0, -400, -200, -1000]
false


[ Info:  started timer at: 2023-03-24T10:59:00.139


125
1
-35460.27740187229
1235.3149587403705
-------------------------
125[0, -600, -200, -1000]


[ Info:           88.8488366s: 1 minute, 28 seconds, 848 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:00:29.086


125
1
-38736.28909674942
1401.774477367374


[ Info:           87.6849496s: 1 minute, 27 seconds, 684 milliseconds


-------------------------
125[0, -800, -200, -1000]
false


[ Info:  started timer at: 2023-03-24T11:01:56.882


125
1
-41752.00911596124
1580.4613164813204
-------------------------
125[0, -1000, -200, -1000]


[ Info:           86.4135494s: 1 minute, 26 seconds, 413 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:03:23.400


125
1
-44402.188045130824
1846.3728034275468
-------------------------
125[0, -1200, -200, -1000]


[ Info:            82.818129s: 1 minute, 22 seconds, 818 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:04:46.353


125
1
-46724.72481405799
2009.9740875732816
-------------------------
125[0, -1400, -200, -1000]


[ Info:           81.3353993s: 1 minute, 21 seconds, 335 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:06:07.803


125
1
-48868.558307587125
2124.9236693555545
-------------------------
125[0, -1600, -200, -1000]


[ Info:           79.1884025s: 1 minute, 19 seconds, 188 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:07:27.100


125
1
-50828.03883082937
2300.7501031700112
-------------------------
150[0, -200, -200, -1000]


[ Info:           77.9386559s: 1 minute, 17 seconds, 938 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:08:45.163


150
1
-37698.157628912246
1272.1453138517081
-------------------------
150[0, -400, -200, -1000]


[ Info:          106.4064814s: 1 minute, 46 seconds, 406 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:10:31.695


150
1
-41185.008495630434
1349.4468149413804
-------------------------
150[0, -600, -200, -1000]


[ Info:          106.4707872s: 1 minute, 46 seconds, 470 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:12:18.288


150
1
-44606.27170477395
1449.6172171548533
-------------------------
150[0, -800, -200, -1000]


[ Info:          105.8284279s: 1 minute, 45 seconds, 828 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:14:04.221


150
1
-47830.515008646384
1563.9610629374422
-------------------------
150[0, -1000, -200, -1000]


[ Info:          106.9751335s: 1 minute, 46 seconds, 975 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:15:51.319


150
1
-50767.435581160425
1805.2094227420519
-------------------------
150[0, -1200, -200, -1000]


[ Info:          102.3731466s: 1 minute, 42 seconds, 373 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:17:33.819


150
1
-53430.95869326788
1969.7723007529453
-------------------------
150[0, -1400, -200, -1000]


[ Info:          101.4736186s: 1 minute, 41 seconds, 473 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:19:15.390


150
1
-55827.38423255992
2210.3787370966543
-------------------------
150[0, -1600, -200, -1000]


[ Info:           96.3526715s: 1 minute, 36 seconds, 352 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:20:51.852


150
1
-57970.43925723952
2377.3333401661403
-------------------------
175[0, -200, -200, -1000]
false


[ Info:           94.8653538s: 1 minute, 34 seconds, 865 milliseconds
[ Info:  started timer at: 2023-03-24T11:22:26.796


175
1
-43400.71920966422
1378.1510783462695
-------------------------
175[0, -400, -200, -1000]


[ Info:          124.1900635s: 2 minutes, 4 seconds, 190 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:24:31.100


175
1
-46942.61224440638
1436.2023729302864
-------------------------
175[0, -600, -200, -1000]


[ Info:          123.8670946s: 2 minutes, 3 seconds, 867 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:26:35.080


175
1
-50391.15403914472
1494.7189253856648
-------------------------
175[0, -800, -200, -1000]


[ Info:          124.2023845s: 2 minutes, 4 seconds, 202 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:28:39.394


175
1
-53737.61134586099
1572.7445369157526
-------------------------
175[0, -1000, -200, -1000]


[ Info:          123.3993221s: 2 minutes, 3 seconds, 399 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:30:42.916


175
1
-56913.73545437532
1757.862808018099
-------------------------
175[0, -1200, -200, -1000]


[ Info:          121.3118205s: 2 minutes, 1 second, 311 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:32:44.343


175
1
-59843.49954090809
1936.9575005528072
-------------------------
175[0, -1400, -200, -1000]


[ Info:          119.8331534s: 1 minute, 59 seconds, 833 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:34:44.273


175
1
-62481.93850928339
2194.5559266918654
-------------------------
175[0, -1600, -200, -1000]


[ Info:           115.689135s: 1 minute, 55 seconds, 689 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:36:40.074


175
1
-64874.35031956309
2347.3068502648625
-------------------------
200[0, -200, -200, -1000]


[ Info:          113.6905117s: 1 minute, 53 seconds, 690 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:38:33.868


200
1
-49138.46815662711
1474.159358057602
-------------------------
200[0, -400, -200, -1000]


[ Info:           141.845881s: 2 minutes, 21 seconds, 845 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:40:55.830


200
1
-52654.51456643162
1486.8462390678615


[ Info:           142.197076s: 2 minutes, 22 seconds, 197 milliseconds


-------------------------
200[0, -600, -200, -1000]
false


[ Info:  started timer at: 2023-03-24T11:43:18.177


200
1
-56123.68098975221
1563.2684659423464
-------------------------
200[0, -800, -200, -1000]


[ Info:          141.4754028s: 2 minutes, 21 seconds, 475 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:45:39.773


200
1
-59528.84357412325
1619.6881636371477
-------------------------
200[0, -1000, -200, -1000]


[ Info:          141.6563892s: 2 minutes, 21 seconds, 656 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:48:01.568


200
1
-62873.11673908163
1746.0211280334306
-------------------------
200[0, -1200, -200, -1000]


[ Info:          140.2660769s: 2 minutes, 20 seconds, 266 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:50:21.942


200
1
-65997.22182084828
1900.7767170077748
-------------------------
200[0, -1400, -200, -1000]


[ Info:          139.5327274s: 2 minutes, 19 seconds, 532 milliseconds


false


[ Info:  started timer at: 2023-03-24T11:52:41.586


200
1
-68906.14486464932
2099.7385924251785
-------------------------
200[0, 

[ Info:          135.3465129s: 2 minutes, 15 seconds, 346 milliseconds


-1600, -200, -1000]
false


[ Info:  started timer at: 2023-03-24T11:54:57.052


200
1
-71579.87049125024
2295.667308404637
-------------------------


[ Info:          133.5162528s: 2 minutes, 13 seconds, 516 milliseconds


In [38]:
df

136×8 DataFrame
 Row │ Units  n    s        m       f        lambda  mean      std     
     │ Any    Any  Any      Any     Any      Any     Any       Any     
─────┼─────────────────────────────────────────────────────────────────
   1 │ 200.0  0.0  -1600.0  -200.0  -1000.0  1.0     -71579.9  2295.67
   2 │ 200.0  0.0  -1400.0  -200.0  -1000.0  1.0     -68906.1  2099.74
   3 │ 200.0  0.0  -1200.0  -200.0  -1000.0  1.0     -65997.2  1900.78
   4 │ 200.0  0.0  -1000.0  -200.0  -1000.0  1.0     -62873.1  1746.02
   5 │ 200.0  0.0  -800.0   -200.0  -1000.0  1.0     -59528.8  1619.69
   6 │ 200.0  0.0  -600.0   -200.0  -1000.0  1.0     -56123.7  1563.27
   7 │ 200.0  0.0  -400.0   -200.0  -1000.0  1.0     -52654.5  1486.85
   8 │ 200.0  0.0  -200.0   -200.0  -1000.0  1.0     -49138.5  1474.16
   9 │ 175.0  0.0  -1600.0  -200.0  -1000.0  1.0     -64874.4  2347.31
  10 │ 175.0  0.0  -1400.0  -200.0  -1000.0  1.0     -62481.9  2194.56
  11 │ 175.0  0.0  -1200.0  -200.0  -1000.0  1.0     -59843.5  1936.96
  ⋮  │   ⋮     ⋮      ⋮       ⋮        ⋮       ⋮        ⋮         ⋮
 127 │ 5.0    0.0  -400.0   -200.0  -1000.0  1.0     -3084.26  738.209
 128 │ 5.0    0.0  -200.0   -200.0  -1000.0  1.0     -2518.28  638.515
 129 │ 3.0    0.0  -1600.0  -200.0  -1000.0  1.0     -3941.8   1100.95
 130 │ 3.0    0.0  -1400.0  -200.0  -1000.0  1.0     -3659.67  1031.5
 131 │ 3.0    0.0  -1200.0  -200.0  -1000.0  1.0     -3369.16  951.347
 132 │ 3.0    0.0  -1000.0  -200.0  -1000.0  1.0     -3092.16  864.881
 133 │ 3.0    0.0  -800.0   -200.0  -1000.0  1.0     -3022.93  883.322
 134 │ 3.0    0.0  -600.0   -200.0  -1000.0  1.0     -2519.87  761.85
 135 │ 3.0    0.0  -400.0   -200.0  -1000.0  1.0     -2147.36  661.218
 136 │ 3.0    0.0  -200.0   -200.0  -1000.0  1.0     -1767.92  572.644
                                                       115 rows omitted

In [39]:
using CSV
CSV.write("valueiteration_MAX_200.csv", df)

"valueiteration_MAX_200.csv"